### ISSUE TITLE
Secondary Rate Limit detector misses message 

### ISSUE THREAD

**Issue by jporzucek** [gofri/go-github-ratelimit#14]
At the moment Secondary Rate Limit detector checks for single [message](https://github.com/gofri/go-github-ratelimit/blob/c98c9d2db8b315546e048e0ce7a62cd66c23fb31/github_ratelimit/detect.go#L16) only which apparently corresponds do POST API requests (content creation). When one hits Secondary Rate Limiter with GET request, the following message is returned by the API:  `You have exceeded a secondary rate limit. Please wait a few minutes before you try again.`

**Comment by bl-robinson** [comment]
I think this is a bit more or a problem than just this PR handles. 

We have just today seen the message from github become 
```You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later. If you reach out to GitHub Support for help, please include the request ID <unique id>.```

Is there a better way of dealing with this that is more resilient to the message changing?

**Comment by gofri** [comment]
Thanks for your comments!
I added the message check because of conflicts with the primary rate limit.
I tried to follow the API docs but I guess it's too dynamic.

It seems like all the messages start with the same sentence though, so checking for HasSuffix() should work.

I'm on vacation and not gonna have PC access for a few weeks, so please feel free to implement it if it sounds good to you and I'll approve it from my phone.

**Comment by bl-robinson** [comment]
Hey both. I just opened https://github.com/gofri/go-github-ratelimit/pull/16 I had implemented it before you responded @gofri happy for you to use it or not. It just worked for me on our internal tests.

**Comment by gofri** [comment]
Perfect!

**Comment by gofri** [comment]
Merged 😄
Thank you both for your contribution!
I'll try to make a new tag from my phone now
