### ISSUE TITLE
Multiple transports for Github App?

### ISSUE THREAD

**Issue by NorseGaud** [gofri/go-github-ratelimit#27]
I need to support https://github.com/google/go-github?tab=readme-ov-file#as-a-github-app and it indicates that I'm setting `github.NewClient(&http.Client{Transport: itr})`, but I'm already doing `github.NewClient(rateLimit)` so I can use this. Is there a recommended approach to merge the transports or use both of these somehow?

**Comment by NorseGaud** [comment]
Maybe I can override https://github.com/gofri/go-github-ratelimit/blob/9d9726540b07a6a728cc6beb4a28cdc8a3a8f91a/github_ratelimit/ratelimit.go#L20 with the same one I'm using for `ghinstallation.NewKeyFromFile`. I'll give it a try...

**Comment by gofri** [comment]
Hey @NorseGaud,
Replying from my phone so sorry for not being able to dig into the actual code.
The general idea with Go's round-trippers is that you can stack them by setting one as the Base of another (you can see an example in go-github-ratelimit's client).

I hope it helps

**Comment by NorseGaud** [comment]
@gofri , "you can see an example in go-github-ratelimit's client" -- can you point me to that? I still have no idea how to achieve this :(

**Comment by gofri** [comment]
@NorseGaud sure.
The [SenodaryRateLimitWaiter](https://github.com/gofri/go-github-ratelimit/blob/main/github_ratelimit%2Fratelimit.go#L18) implements the http.RoundTripper interface, so you can use it as the Transport for any other http client.
In your case, you can use NewSecondaryRateLimitWaiter(itr), and use itd result as your http.Transport, instead of itr.
I hope that helps :)
